---
abstract: 'Extends Path::Iterator::Rule with custom rule subroutines that make it easy to add RT ticket data as rules.'
author:
  - 'Robert Blackwell <robert@robertblackwell.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.132140'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Path-Iterator-Rule-RT
provides:
  Path::Iterator::Rule::RT:
    file: lib/Path/Iterator/Rule/RT.pm
    version: '0.04'
requires:
  Path::Iterator::Rule: '1.008'
  RT::Client::REST: '0.45'
resources:
  repository: https://github.com/rblackwe/Path-Iterator-Rule-RT
version: '0.04'
